Updated the Dev branch
anthonyLuttrell/RedditStatsBot pull request #11
Opened 2023-11-20 11:47 UTC by sushpawar001

Added docstrings according to the PEP. Optimized a few functions.

2023-11-21 16:37 UTC, anthonyLuttrell requested changes
Please fix the docstring syntax and remove the if main check and I will try to get this merged into the master branch soon.

2023-11-21 16:37 UTC, anthonyLuttrell commented on main.py
> +    Deletes and sets user flair, then updates the wiki pages.
Please use the Google style guide as a reference for docstrings

https://google.github.io/styleguide/pyguide.html#s3.8-comments-and-docstrings

> A docstring should be organized as a summary line (one physical line not exceeding 80 characters) terminated by a period, question mark, or exclamation point. When writing more (encouraged), this must be followed by a blank line, followed by the rest of the docstring starting at the same cursor position as the first quote of the first line.

2023-11-21 16:37 UTC, anthonyLuttrell commented on main.py
> +if __name__ == "__main__":
Remove this for now, the dev_oop branch will include a main function.

2023-11-22 07:09 UTC, sushpawar001 commented
Please check it out. Made the requested changes.

2023-11-23 17:32 UTC, merged